import demoVideo from "./DemoVideo/TestCaseRecommender.mp4";
import QualityAssuranceEngineer from '../images/Test Case Recommender/icons8-approval-100 1.svg'
import ProjectManagers from '../images/Test Case Recommender/icons8-manager-100 (2) 3.svg'
import DevOpsTeamsLeads from '../images/Test Case Recommender/icons8-leader-100 1.svg'
import BusinessAnalysts from '../images/Test Case Recommender/icons8-admin-100 4.svg'

import ImprovedTestCoverage from '../images/Test Case Recommender/icons8-test-100 1.svg'
import StandardizationandConsistency from '../images/Test Case Recommender/icons8-neutral-trading-100 1.svg'
import EnhancedQuality from '../images/Test Case Recommender/icons8-quality-100 1.svg'
import FasterTimetoMarket from '../images/Test Case Recommender/icons8-market-100 1.svg'
import EnhancedCollaborationandVisibility from '../images/Test Case Recommender/icons8-user-groups-100 2.svg'
import CostSavings from '../images/Test Case Recommender/icons8-money-box-100 2.svg'
import bannerImg from '../images/Test Case Recommender/Test Care Recommender.svg'


const iconSize = {
  height: "5rem",
  width: "5rem",
  color: "#dc848d",
};
const iconSizeBO = {
  height: "5rem",
  width: "5rem",
  color: "#dc848d",
  // border: "solid #dc848d 3px",
  // margin: "0px 10px",
  // padding: "30px 50px",
  // borderRadius: "10px",
  // boxShadow: "0px 8px 16px 0px red"
}
export const TestCaseRecommender = {
  title: "Shelf detect bot",
  content:
    " A cutting-edge solution leveraging deep learning to identify PepsiCo drinks on shelves within warehouse or retail environments. It provides real-time detection, enabling precise inventory management and data-driven insights for optimized product placement and operational efficiency.",
  img: bannerImg,
  BusinessCase: [
    "Automating test case creation for software development is pivotal for maintaining high-quality standards in the final product. Shelf Detect Bot streamlines this process by employing advanced algorithms to identify white spaces in PepsiCo inventory shelf images. It reduces the time and errors associated with manual test case creation, ensuring comprehensive coverage of relevant test scenarios.",
  ],
  targetUsers: [
    {
      title: "Warehouse Managers",
      description:
        " Responsible for overseeing inventory management and logistics within warehouses, warehouse managers can use the Shelf Detection Bot to ensure accurate tracking of PepsiCo drink inventory levels and optimize shelf organization for efficient storage and retrieval.",
      iconSrc: <img src={QualityAssuranceEngineer} width="70px" alt='' />
    },
    {
      title: "Retail Store Owners",
      description:
        "Owners and managers of retail stores can leverage the bot to monitor product placement and availability on shelves, ensuring that PepsiCo drinks are prominently displayed to maximize sales and customer satisfaction.",
      iconSrc: <img src={ProjectManagers} width="70px" alt='' />
    },
    {
      title: "Supply Chain Analysts",
      description:
        " Professionals involved in analyzing supply chain data can use the insights generated by the bot to assess inventory trends, forecast demand for PepsiCo drinks, and identify opportunities for optimizing distribution and replenishment strategies.",
      iconSrc: <img src={DevOpsTeamsLeads} width="70px" alt='' />
    },
    {
      title: "Marketing Managers",
      description:
        "Marketing managers can utilize the bot's analytics and reports to understand consumer preferences and behavior related to PepsiCo drinks, enabling them to develop targeted marketing campaigns and promotions to drive sales and brand engagement.",
      iconSrc: <img src={BusinessAnalysts} width="70px" alt='' />
    },
  ],
  businessOutcomes: [
    {
      title: "Increased Sales",
      description:
        [" Optimized product placement facilitated by the bot leads to increased visibility and accessibility of PepsiCo drinks, resulting in higher sales volumes and revenue generation."],
      image: <img src={ImprovedTestCoverage} width="100px" style={iconSizeBO} />
    },
    {
      title: "Cost Savings",
      description:
        ["Enhanced inventory management and reduced stockouts achieved through the bot's real-time detection capabilities lead to cost savings by minimizing overstocking."],
      image: <img src={StandardizationandConsistency} width="100px" style={iconSizeBO} />
    },
    {
      title: "Data-Driven Decisions",
      description:
        [" The actionable insights provided by the bot's analytics empower businesses to make informed decisions regarding inventory optimization."],
      image: <img src={EnhancedQuality} width="100px" style={iconSizeBO} />
    },
    {
      title: "Customer Experience",
      description:
        ["By ensuring consistent availability of PepsiCo drinks on shelves and optimizing shelf layouts based on consumer preferences, the bot contributes to an enhanced customer experience."],
      image: <img src={FasterTimetoMarket} width="100px" style={iconSizeBO} />
    },
    {
      title: "Competitive Advantage",
      description:
        ["By leveraging the Shelf Detection Bot to optimize inventory management and product placement, businesses can gain a competitive edge in the market by offering a superior shopping experience."],
      image: <img src={EnhancedCollaborationandVisibility} width="100px" style={iconSizeBO} />
    },
    {
      title: "Brand Loyalty and Trust",
      description:
        [": Consistently ensuring the availability of PepsiCo drinks on shelves through accurate inventory management enhances brand loyalty among consumers"],
      image: <img src={CostSavings} width="100px" style={iconSizeBO} />
    },
  ],
  solutionHighlights: [
    "Designing the bot to perform real-time detection, enabling instant identification of PepsiCo drinks as they enter or move within the premises.",
    "Seamless integration with warehouse or retail management systems to access relevant data for analysis and to ensure consistency in reporting.",
    " Utilizing Power BI for in-depth analysis of the detected data, enabling stakeholders to gain valuable insights into product distribution, inventory management, and consumer trends.",
    " Building the bot with scalability in mind to accommodate varying sizes of warehouses or retail marts, as well as potential expansion of the operation.",
  ],
  summary: [
    {
      title: "Challenges",
      details: [
        "PepsiCo drinks may come in various packaging designs and sizes, leading to challenges in accurately detecting and identifying them. ",
        "Warehouse and retail mart environments can be dynamic, with varying lighting conditions, obstructions, and clutter.",
        "Ensuring that the code dynamically constructs the correct Blob URLs and handles any changes in storage configuration or naming conventions is crucial.",
        "Handling sensitive data related to product inventory and consumer behavior requires stringent measures to ensure data privacy and security. ",
        "Retrieving images from Blob storage may introduce latency compared to local file access. Optimizing image retrieval and processing pipelines within the function app to minimize latency and maximize throughput while adhering to resource constraints presents a performance optimization challenge.",
      ],
    },
    {
      title: "Building Solution",
      details: [
        <div><b>Deep Learning Model Development:</b> Invest in developing a robust deep learning model (e.g., YOLOv5, Faster R-CNN) tailored for detecting PepsiCo drinks on shelves within warehouse or retail environments. This involves training the model on annotated image datasets to accurately identify product placements.       </div>,
        <div><b>Data Collection and Annotation:</b>Gather a diverse dataset of images depicting PepsiCo drink shelves under various conditions (e.g., different lighting, angles, shelf layouts). Annotate these images to provide ground truth labels for training the deep learning model effectively.</div>,
        <div><b>Integration with Warehouse:</b> Integrate the bot with existing warehouse or retail management systems to access real-time inventory data and shelf layouts. </div>,
        <div><b>Real-time Detection Pipeline:</b>Implement a real-time detection pipeline that continuously processes incoming images from cameras installed in the warehouse or retail mart. This pipeline should efficiently analyze each image, detect PepsiCo drinks, and extract relevant metadata for further analysis.</div>,
      ],
    },
    {
      title: "Outcomes",
      details: [
        <div><b>Enhanced Inventory Management:</b> By accurately identifying PepsiCo drinks on shelves in real-time, the bot enables more precise inventory tracking and management. This leads to reduced stockouts, minimized overstocking, and optimized shelf replenishment cycles.</div>,
        <div><b>Improved Product Placement:</b>Insights derived from the bot's analysis help optimize product placement strategies within the warehouse or retail environment. </div>,
        <div><b>Data-driven Decision Making: </b> The analytics and reports generated by the bot empower stakeholders to make data-driven decisions regarding inventory optimization, marketing strategies, and shelf layout designs.</div>,
        <div><b>Operational Efficiency: </b> Automation of shelf detection and analysis tasks streamlines operational workflows and reduces manual effort. </div>,],
    },
  ],
  demo: {
    link: { demoVideo },
  },
  tryit: {
    link: "https://testcaserecommenderfrontend.azurewebsites.net/",
  },

  FAQs: [
    {
      question: "How does the AI-driven client profiling work?",
      answer: "The AI-driven client profiling works by leveraging OpenAI to ask targeted questions to clients, swiftly gathering information on their priorities, challenges, goals, and risks. This data is then matched with business value maps, enabling the rapid delivery of personalized solutions."
    },
    {
      question: "What are the benefits of using AI for client profiling?",
      answer: "Using AI for client profiling offers several benefits, including streamlined client profiling, faster delivery of personalized solutions, improved accuracy in client profiles and solutions, enhanced efficiency and productivity, increased sales conversion rates, and a competitive advantage in the market."
    },
    {
      question: "How does the solution improve sales productivity?",
      answer: "The solution improves sales productivity by reducing the time and resources required for client profiling, enabling the sales team to focus on more strategic activities. Additionally, the quick provision of tailored solutions enhances response times and customer satisfaction, leading to increased sales conversion rates and revenue."
    },
    {
      question: "What role does OpenAI play in the solution?",
      answer: "OpenAI plays a crucial role in the solution by automating and streamlining the client profiling process through targeted questioning. It generates data-driven insights into client priorities, challenges, goals, and risks, facilitating the delivery of personalized solutions in record time."
    },
    {
      question: "How accurate are the client profiles generated by the solution?",
      answer: "The client profiles generated by the solution are highly accurate due to the precise and relevant information gathered through OpenAI-driven questioning. This ensures that the solutions provided are well-aligned with the clients' needs and preferences."
    }
  ]
};

export default TestCaseRecommender;
