// import { Container } from "@mui/material";
import "./css/virtualtool.css";
// import { useEffect, useState } from "react";
// import { useParams } from "react-router-dom";
// import AOS from "aos";
// import "aos/dist/aos.css";
// // import ProductDemo from "../../product-dashboard/ProductDemo";
// import VideoDemo from "./VideoDemo";
import gif from "./Tools/bot.gif";
import FAQ from "./FAQ";
import ContactForm from "./contactForm";
import "./css/contactform.css";
import img1 from "./icon/icon-bi-analytics.svg";
import IndustriesList from "./IndustryItem";
import KeyFeaturesSection from "./KeyFeaturesSection";

const VirtualAssistantTool = () => {
  return (
    <>
      {/* <p>Welcome</p> */}
      <section className="toolinformation">
        {/* <Container fluid> */}
        <div className="container">
          <div className="grids">
            <div className="top">
              <div className="heading">
                <span>Advanced AI-powered Support</span>
              </div>
              <div className="heading_inner">
                <p>
                  Revolutionize query resolution, elevate customer satisfaction,
                  and empower human agents for more impactful tasks with your
                  intelligent virtual assistant tool.
                </p>
              </div>

              {/* <div className="buttons">
              <div className="get_guid">
                <button>Get the guide</button>
              </div>
              <div className="freechat">
                <button>Free consultation on chatbots</button>
              </div>
            </div> */}
              <div className="images">
                <div className="imageone"></div>
                <div className="imagetwo"></div>
              </div>
            </div>
          </div>
        </div>

        {/* <VideoDemo link={productDetails.demo.link} /> */}
        {/* </Container> */}
      </section>

      <div className="video">
        <h2 className="aurora">
          Meet Aurora Borea, our chatbot for intelligent customer support
        </h2>
        <iframe
          style={{ display: "block", margin: "0 auto 100px", maxWidth: "100%" }}
          width="800"
          height="450"
          src="https://www.youtube.com/embed/LM6yn09axSc?si=BAXVPXV3aYjitC2V"
          title="YouTube video player"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowFullScreen
        ></iframe>
      </div>

      {/* <div className="quick-block">
        <div className="head-block-center" style={{marginBottom:"10px"}}>
          <h2 className="headblock">
            AI-Powered Virtual Assistant: Key Features
          </h2>
        </div>
        <div className="text-block-center" style={{marginBottom:"10px"}}>
          Revolutionize customer support and enhance productivity with your
          virtual assistant solution.
        </div>
      </div>

      <section className="section-text-image type-center __xs-pic-size __w-50 __image-right">
        <div className="section-text-image-inner">
          <div className="setion-text-image__details">
            <h3 className="section-text-image__title">
              24/7 Personalized Customer Assistance
            </h3>
            <div className="section-text-image__description">
              <ul>
                <li>
                  Addressing common queries about the company’s services and
                  products tailored to the specific client’s request
                </li>
                <li>
                  Round-the-clock availability during festive seasons and busy
                  times
                </li>
                <li>Personalized human-like responses</li>
                <li>
                  Immediate comprehensive response to the query based on the
                  company’s proprietary knowledge base
                </li>
                <li>Virtual assistant tool for multilingual support</li>
                <li>Recommendations concerning the topic generated by ML</li>
              </ul>
            </div>
          </div>

          <div className="section-text-image__figure">
            <img src={gif} alt="" />
          </div>
        </div>

        <div className="section-text-image-inner">
          <div className="section-text-image__figure">
            <img src={gif} alt="" />
          </div>
          <div className="setion-text-image__details">
            <h3 className="section-text-image__title">
              Automated Support for Sales Teams
            </h3>
            <div className="section-text-image__description">
              <ul>
                <li>
                  Automated Q&amp;A with customers to free up your human agents
                  for more intelligent and urgent tasks
                </li>
                <li>Effective appointment scheduling across time zones</li>
                <li>
                  Fast data transfer to the sales team (conversation history and
                  context)
                </li>
                <li>
                  Automatic email notifications to the sales team and customer
                </li>
              </ul>
            </div>
          </div>
        </div>

        <div className="section-text-image-inner">
          <div className="setion-text-image__details">
            <h3 className="section-text-image__title">
              Streamlined Appointment Scheduling
            </h3>
            <div className="section-text-image__description">
              <ul>
                <li>Efficient handling of back-and-forth communication</li>
                <li>Scheduling tasks across time zones</li>
                <li>Calendar integration</li>
              </ul>
            </div>
          </div>

          <div className="section-text-image__figure">
            <img src={gif} alt="" />
          </div>
        </div>

        <div className="section-text-image-inner">
          <div className="section-text-image__figure">
            <img src={gif} alt="" />
          </div>
          <div className="setion-text-image__details">
            <h3 className="section-text-image__title">
              Seamless Integration with CRM
            </h3>
            <div className="section-text-image__description">
              <ul>
                <li>
                  Automated data extraction and summarization
                  from&nbsp;conversations
                </li>
                <li>Prompt creation of CRM records as required</li>
                <li>Enhanced data precision</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="section-text-image-inner">
          <div className="setion-text-image__details">
            <h3 className="section-text-image__title">
              Text and Voice Recognition Capabilities
            </h3>
            <div className="section-text-image__description">
              <ul>
                <li>
                  The ability to audio communicate your needs
                  <br />
                  to a chatbot
                </li>
                <li>Fluid and natural customer experience</li>
              </ul>
            </div>
          </div>
          <div className="section-text-image__figure">
            <img src={gif} alt="" />
          </div>
        </div>
      </section> */}

      <KeyFeaturesSection />


      <section className="section-industries">
        <div className="industries__inner" style={{marginTop:"10px",marginBottom:"0px"}}>
          <h2 className="head-block-center">Advantages of Virtual Assistant</h2>
        </div>

        <div class="text-block-center" style={{marginTop:"-10px", marginBottom:"20px"}}>
          Virtual assistant software development allows you to delegate non-core
          tasks to a chatbot and concentrate on growing your business.
        </div>

        <IndustriesList />

        <div className="text-block-center" style={{marginTop:"50px"}}>
      <span className="gap">Ready to learn more about chatbot development?</span>
    </div>

        <div className="block__action"> <a href="#section-contacts" class="btn btn-empty">Contact us</a></div>

        <FAQ />
        <ContactForm />
      </section>
    </>
  );
};

export default VirtualAssistantTool;
